import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { FloatingControls } from "@/components/FloatingControls";
import { CTA } from "@/components/CTA";
import { ThemeProvider } from "./theme-provider";
import ProgressLoader from "./client";
import Preloader from "@/components/Preloader";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sarker Trims Limited | Quality Accessories Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <ThemeProvider>
          <ProgressLoader color="#ffffff" showSpinner={false} />
          <Preloader />
          <div className="bg-slate-50 dark:bg-slate-950 min-h-screen text-slate-900 dark:text-slate-100 transition-colors duration-300">
            <Header />

            <main>
              {children}
            </main>

            <CTA />

            <Footer />

            <FloatingControls />
          </div>
        </ThemeProvider>
      </body >
    </html >
  );
}
